# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4c7a4b045e4d3f53cef7fc852e677b53be3018619c6535d3da8785df1ba01bf2fb0107d0f23ebead70e357ddb369fb8124d5d41e2b902c98c8120fa484f119a9

test:
  secret_key_base: 2a3ffdd852cb3a9538e384c9c56c778ba7b181a7b9ec59401ee9758fdf6fa537a9b00362f0c49dc290e366b40eb684ec6372815ab5bd0ef78d5e3a52010cffbd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
